spring:
  flyway.enabled: true
  flyway:
    locations: classpath:db.migrations
    schemas: file
    url: jdbc:postgresql://localhost:5432/countbytesdb
    user: pguser
    password: pgpass
    baselineOnMigrate: true
  datasource:
    username: pguser
    password: pgpass
    url: jdbc:postgresql://localhost:5432/countbytesdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          new_generator_mappings: false
    show-sql: true
  application:
    name: readandcount
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Demo-realm
springdoc:
  swagger-ui:
    oauth:
      client-id: springboot-microservice
      client-secret: QTEqwJp5740HihWQb2smtFZtlC26vkOe

grant-type-key: password
name-key: employee1
password-key: mypassword
realm-key: Demo-realm
server-url-key: http://localhost:8081
client-id: springboot-microservice
client-secret: QTEqwJp5740HihWQb2smtFZtlC26vkOe

server:
  port: 8081

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        jdbc:
          core: DEBUG
